spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jimirene
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect