spring:
  datasource:
    url: jdbc:sqlserver://jimirene-clinic.database.windows.net:1433;database=jimirene;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: jimirene@jimirene-clinic
    password: jimclinic@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

  server:
    port: 9090